trigger:
- master

pool:
  name: Default

steps:
- script: az login --service-principal -u df551e12-dfec-4169-8feb-b1e7c3a30887 -p 3~D8Q~JDeNBXKhjrDbbejGmNANgxbynD6EjICaMD --tenant 84f1e4ea-8554-43e1-8709-f0b8589ea118
  displayName: 'az login'
- script: az acr login --name eloacrprd
  displayName: 'az acr login'
- script: sudo docker build -t eloacrprd.azurecr.io/0.001:latest $(System.DefaultWorkingDirectory)
  displayName: 'docker build'
- script: sudo docker push eloacrprd.azurecr.io/0.001:latest
  displayName: 'docker push'